### ISSUE TITLE
Files from ethernity4ever's site may be missing or incorrect

### ISSUE THREAD

**Issue by TropicSapling** [NN-Dev-Team/Nordic-Network#3]
FYI I've gotten the html, css and some js code by using Inspect Element on the site, so it's probably a bit incorrect. Tell me if you know any better way of getting it, also @ethernity4ever tell me if you've managed to get the code via Wordpress :)

**Comment by ghost** [comment]
You can get the html of a site by sending a get request (in node, [`http.get(url, callback)`](http://devdocs.io/node_lts/http#http_http_get_options_callback) will return the html of the website.)

Then parse for links to js/css and get those as well.

Honestly though, I have no idea what this issue is about.

**Comment by TropicSapling** [comment]
@theonlygusti Thanks :)

I know this might be a bit of a weird issue but @ethernity4ever has made the design for the website using WordPress, and I have coded some of the js stuff. And we need to put it all together instead of having it seperate, and I would also like to have the code for the design on GitHub because it's easier for me to make the js code then :)

**Comment by TropicSapling** [comment]
I'm closing this for now but will reopen again when @ethernity4ever has found a way to get the code :)

**EDIT:** Not happening since @ethernity4ever left the team. (This edit was written 27/9/2016, ethernity left quite a while earlier though, probably sometime during Spring)
